server:
  port: 8090

jdac:
  baseUrl: http://localhost:8080/service/backlogic/example
  basePackage: net.backlogic.persistence.springboot.classic.repository
  logRequest: true
  jwtProvider:
    class: net.backlogic.persistence.client.auth.SimpleJwtProvider
    jwt: " "

logging:
  level:
    root: INFO

debug: true